language: go
go:
  - 1.6
services:
  - redis
install:
  - go get github.com/jstemmer/go-junit-report
  - go get github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml
  - ./build static
  - sudo ./install
script:
  - ./test
